/** Declaration file generated by dts-gen */

declare module 'appmetrics' {

	export const VERSION: string

	export const lrtime: any

	export function configure(options: any): void

	export function disable(data: any): void

	export function emit(topic: any, data: any): void

	export function enable(data: any, config?: any): void

	export function getJSONProfilingMode(): any

	export function getObjectHistogram(): any

	export function getOption(): any

	export function localConnect(): any

	export function monitor(): any

	export function nativeEmit(): any

	export function sendControlCommand(): any

	export function setConfig(data: any, config: any): void

	export function setHeadlessZipFunction(): any

	export function setJSONProfilingMode(val: any): void

	export function setOption(): any

	export function spath(): any

	export function start(): any

	export function stop(): any

	export function transactionLink(linkName: any, callback: any): any

	export function writeSnapshot(arguments: any, ...args: any[]): any

}

