/** Declaration file generated by dts-gen */

declare module 'appmetrics-dash' {

	export function attach(options: any, ...args: any[]): any;

	export function monitor(options: any): any;

}

