/** Declaration file generated by dts-gen */

declare module 'clui' {

	export function Clear(clear: any): void

	export function Gauge(value: any, maxValue: any, width: any, dangerZone: any, suffix: any): any

	export function Line(defaultBuffer: any): any

	export function LineBuffer(userOptions: any): any

	export function Progress(width: any): any

	export function Sparkline(points: any, suffix: any): any

	export function Spinner(message: any, style: any): any

	export function Table(): any

}

