/** Declaration file generated by dts-gen */

declare module 'pmx' {

	export const AVAILABLE_AGG_TYPES: string[];

	export const AVAILABLE_MEASUREMENTS: string[];

	export const default_aggregation: string;

	export function action(action_name: any, opts: any, fn: any): any;

	export function catchAll(opts: any): any;

	export function catchPorts(...args: any[]): any;

	export function catchTraffic(...args: any[]): any;

	export function configureModule(opts: any): void;

	export function detectV8Profiler(cb: any): any;

	export function emit(name: any, data: any): any;

	export function enableProbe(custom_namespace: any): any;

	export function enableProbes(custom_namespace: any): any;

	export function exposeProfiling(pmx: any, profiler_path: any): any;

	export function expressErrorHandler(): any;

	export function getConf(): any;

	export function getEnv(): any;

	export function getPID(file: any): any;

	export function http(opts: any, ...args: any[]): any;

	export function init(opts: any): any;

	export function initModule(opts: any, cb: any): any;

	export function notify(err: any): any;

	export function probe(): any;

	export function resolvePidPaths(filepaths: any): any;

	export function scopedAction(action_name: any, fn: any): any;

	export function stopProbe(): void;

	export function stopProbes(): void;

	export function tracing(pmx: any, opts: any): void;

	export function v8Profiling(pmx: any): any;

	export interface Metric {
		val: () => number
		set: (n: number) => void
		mark: (n?: number) => void
	}

}
