/** Declaration file generated by dts-gen */

declare module 'say' {

	export const baseSpeed: number

	export const child: any

	export const platforms: {
		LINUX: string
		MACOS: string
		WIN32: string
	}

	export function Say(...args?: any[]): any

	export function buildExportCommand(...args?: any[]): void

	export function buildSpeakCommand(...args?: any[]): void

	export function convertSpeed(...args?: any[]): void

	export function runStopCommand(...args?: any[]): void

	export function speak(...args?: any[]): void

	export function stop(...args?: any[]): void

}

