/** Declaration file generated by dts-gen */

declare module 'systeminformation' {

	export function baseboard(callback?: any): any

	export function battery(callback?: any): any

	export function bios(callback?: any): any

	export function blockDevices(callback?: any): any

	export function cpu(callback?: any): any

	export function cpuCache(callback?: any): any

	export function cpuCurrentspeed(callback?: any): any

	export function cpuFlags(callback?: any): any

	export function cpuTemperature(callback?: any): any

	export function currentLoad(callback?: any): any

	export function diskLayout(callback?: any): any

	export function disksIO(callback?: any): any

	export function dockerAll(callback?: any): any

	export function dockerContainerProcesses(containerID?: any, callback?: any): any

	export function dockerContainerStats(containerID?: any, callback?: any): any

	export function dockerContainers(all?: any, callback?: any): any

	export function fsSize(callback?: any): any

	export function fsStats(callback?: any): any

	export function fullLoad(callback?: any): any

	export function getAllData(srv?: any, iface?: any, callback?: any): any

	export function getDynamicData(srv?: any, iface?: any, callback?: any): any

	export function getStaticData(callback?: any): any

	export function graphics(callback?: any): any

	export function inetChecksite(url?: any, callback?: any): any

	export function inetLatency(host?: any, callback?: any): any

	export function mem(callback?: any): any

	export function memLayout(callback?: any): any

	export function networkConnections(callback?: any): any

	export function networkInterfaceDefault(callback?: any): any

	export function networkInterfaces(callback?: any): any

	export function networkStats(iface?: any, callback?: any): any

	export function osInfo(callback?: any): any

	export function processLoad(proc?: any, callback?: any): any

	export function processes(callback?: any): any

	export function services(srv?: any, callback?: any): any

	export function shell(callback?: any): any

	export function system(callback?: any): any

	export function time(): any

	export function users(callback?: any): any

	export function version(): any

	export function versions(callback?: any): any

}

