/** Declaration file generated by dts-gen */

declare module 'tick-tock' {

	export = tick_tock

	class tick_tock {
		constructor(context?: any)

		active(name?: any): any

		adjust(name?: any, time?: any): any

		clear(...args?: any[]): any

		destroy(): any

		end(): any

		setImmediate(name?: any, fn?: any): any

		setInterval(name?: any, fn?: any, time?: any): any

		setTimeout(name?: any, fn?: any, time?: any): any

		tock(name?: any, clear?: any): any

	}

	namespace tick_tock {
		class Timer {
			constructor(timer?: any, clear?: any, duration?: any, fn?: any)

			remaining(): any

			taken(): any

			active(name?: any): any

			adjust(name?: any, time?: any): any

			clear(...args?: any[]): any

			destroy(): any

			end(): any

			setImmediate(name?: any, fn?: any): any

			setInterval(name?: any, fn?: any, time?: any): any

			setTimeout(name?: any, fn?: any, time?: any): any

			tock(name?: any, clear?: any): any

		}

	}

}

