/** Declaration file generated by dts-gen */

declare module 'anomaly' {

	export = anomaly

	class anomaly {
		constructor(...args: any[])

		clear(...args: any[]): any

		mean(...args: any[]): any

		push(...args: any[]): any

		pushMeta(...args: any[]): any

		standardDeviation(...args: any[]): any

		trend(...args: any[]): any

		variance(...args: any[]): any

	}

}


