/** Declaration file generated by dts-gen */

declare module 'everpolate' {
	export function linear(pointsToEvaluate?: any, functionValuesX?: any, functionValuesY?: any): any;

	export function linearRegression(functionValuesX?: any, functionValuesY?: any): any;

	export function polynomial(pointsToEvaluate?: any, functionValuesX?: any, functionValuesY?: any): any;

	export function step(pointsToEvaluate?: any, functionValuesX?: any, functionValuesY?: any): any;
}
