/** Declaration file generated by dts-gen */

declare module 'humanize-plus' {

	export function boundedNumber(num: any, ...args: any[]): any;

	export function br2nl(string: any, ...args: any[]): any;

	export function capitalize(string: any, ...args: any[]): any;

	export function capitalizeAll(string: any): any;

	export function compactInteger(number: number, precision?: number): string;

	export function dictionary(object: any, ...args: any[]): any;

	export function fileSize(bytes: number): string;

	export function formatNumber(number: number, precision?: number): string;

	export function frequency(list: any, verb: any): any;

	export function intComma(number: any, ...args: any[]): any;

	export function intcomma(...args: any[]): any;

	export function intword(number: any, charWidth: any, ...args: any[]): any;

	export function nl2br(string: any, ...args: any[]): any;

	export function normalizePrecision(value: any, base: any): any;

	export function ordinal(value: any): any;

	export function oxford(items: any, limit: any, limitStr: any): any;

	export function pace(value: any, intervalMs: any, ...args: any[]): any;

	export function pluralize(number: any, singular: any, plural: any): any;

	export function times(value: any, ...args: any[]): any;

	export function titleCase(string: any, ...args: any[]): any;

	export function titlecase(...args: any[]): any;

	export function toFixed(value: any, precision: any): any;

	export function truncate(str: any, ...args: any[]): any;

	export function truncateWords(string: any, length: any): any;

	export function truncatenumber(...args: any[]): any;

	export function truncatewords(...args: any[]): any;

}

