/** Declaration file generated by dts-gen */

declare module 'nostradamus' {

	export = nostradamus

	function nostradamus(data?: any, alpha?: any, beta?: any, gamma?: any, period?: any, m?: any): any

	namespace nostradamus {

		function memo(opt?: any): any

	}

}

