/** Declaration file generated by dts-gen */

declare module 'regression' {

	export function _round(number?: any, precision?: any): any

	export function exponential(data?: any, supplied?: any): any

	export function linear(data?: any, supplied?: any): any

	export function logarithmic(data?: any, supplied?: any): any

	export function polynomial(data?: any, supplied?: any): any

	export function power(data?: any, supplied?: any): any

}

