/** Declaration file generated by dts-gen */

declare module 'rolex' {

	export = rolex

	// function rolex(time: number, callback: Function): typeof rolex

	class rolex {
		constructor(duration?: any, repeat?: any, tick?: any)

		aggression(val?: any, ...args?: any[]): any

		count(): any

		duration(val?: any, ...args?: any[]): any

		isLastTick(): any

		repeat(val?: any, ...args?: any[]): any

		runTime(): any

		start(): any

		startTime(): any

		state(): any

		stop(): any

		threshold(val?: any, ...args?: any[]): any

		tick(val?: any, ...args?: any[]): any

		tickTime(n?: any): any

		static clearInterval(timer: NodeJS.Timer): void

		static clearTimeout(timer: NodeJS.Timer): void

		static conflict(): void

		static conflictInterval(): void

		static isRolex(obj?: any): any

		static noConflict(): void

		static setInterval(callback?: any, repeat?: any, ...args?: any[]): NodeJS.Timer

		static setTimeout(callback?: any, after?: any, ...args?: any[]): NodeJS.Timer

	}

}

