/** Declaration file generated by dts-gen */

declare module 'zodiac-ts' {

	export class DoubleExponentialSmoothing {
		constructor(data?: any, alpha?: any)

		computeMeanSquaredError(): any

		getForecast(): any

		optimizeParameter(iter?: any): any

		predict(horizon?: any): any

	}

	export class HoltSmoothing {
		constructor(data?: any, alpha?: any, gamma?: any)

		computeMeanSquaredError(): any

		getForecast(): any

		optimizeParameters(iter?: any): any

		predict(horizon?: any): any

	}

	export class HoltWintersSmoothing {
		constructor(data?: any, alpha?: any, gamma?: any, delta?: any, seasonLength?: any, mult?: any)

		computeMeanSquaredError(): any

		getForecast(): any

		optimizeParameters(iter?: any): any

		predict(): any

		predictAdd(): any

		predictMult(): any

	}

	export class SimpleExponentialSmoothing {
		constructor(data?: any, alpha?: any)

		computeMeanSquaredError(): any

		getForecast(): any

		optimizeParameter(iter?: any): any

		predict(): any

	}

}

