/** Declaration file generated by dts-gen */

declare module 'fingerprintjs2' {
	class fingerprintjs2 {
		constructor(t?: any);

		adBlockKey(e: any): any;

		addBehaviorKey(e: any): any;

		addFlashDivNode(): void;

		availableScreenResolutionKey(e: any): any;

		canvasKey(e: any): any;

		colorDepthKey(e: any): any;

		cpuClassKey(e: any): any;

		doNotTrackKey(e: any): any;

		each(e: any, t: any, i: any): void;

		extend(e: any, t: any): any;

		flashFontsKey(e: any, t: any): any;

		fontsKey(e: any, t: any): any;

		get(e: any): any;

		getAdBlock(): any;

		getAvailableScreenResolution(e: any): any;

		getCanvasFp(): any;

		getDoNotTrack(): any;

		getHardwareConcurrency(): any;

		getHasLiedBrowser(): any;

		getHasLiedLanguages(): any;

		getHasLiedOs(): any;

		getHasLiedResolution(): any;

		getIEPlugins(): any;

		getNavigatorCpuClass(): any;

		getNavigatorPlatform(): any;

		getPixelRatio(): any;

		getRegularPlugins(): any;

		getScreenResolution(e: any): any;

		getTouchSupport(): any;

		getUserAgent(): any;

		getWebglCanvas(): any;

		getWebglFp(): any;

		hardwareConcurrencyKey(e: any): any;

		hasIndexedDB(): any;

		hasLiedBrowserKey(e: any): any;

		hasLiedLanguagesKey(e: any): any;

		hasLiedOsKey(e: any): any;

		hasLiedResolutionKey(e: any): any;

		hasLocalStorage(): any;

		hasMinFlashInstalled(): any;

		hasSessionStorage(): any;

		hasSwfObjectLoaded(): any;

		indexedDbKey(e: any): any;

		isCanvasSupported(): any;

		isIE(): any;

		isWebGlSupported(): any;

		jsFontsKey(e: any, t: any): any;

		languageKey(e: any): any;

		loadSwfAndDetectFonts(e: any): void;

		localStorageKey(e: any): any;

		log(e: any): void;

		map(e: any, t: any, i: any): any;

		openDatabaseKey(e: any): any;

		pixelRatioKey(e: any): any;

		platformKey(e: any): any;

		pluginsKey(e: any): any;

		pluginsShouldBeSorted(): any;

		screenResolutionKey(e: any): any;

		sessionStorageKey(e: any): any;

		timezoneOffsetKey(e: any): any;

		touchSupportKey(e: any): any;

		userAgentKey(e: any): any;

		webglKey(e: any): any;

		x64Add(e: any, t: any): any;

		x64Fmix(e: any): any;

		x64LeftShift(e: any, t: any): any;

		x64Multiply(e: any, t: any): any;

		x64Rotl(e: any, t: any): any;

		x64Xor(e: any, t: any): any;

		x64hash128(e: any, t: any): any;

		static VERSION: string;

	}

	export = fingerprintjs2;
}

